// Generated by https://quicktype.io

class Actores {
  List<Actor> items = new List();

  Actores.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    List<Actor> listActor = jsonList.map((e) => Actor.fromJsonMap(e)).toList();
    items.addAll(listActor);
  }
}

class Actor {
  bool adult;
  int gender;
  int id;
  String knownForDepartment;
  String name;
  String originalName;
  double popularity;
  String profilePath;
  int castId;
  String character;
  String creditId;
  int order;
  String job;

  Actor({
    this.adult,
    this.gender,
    this.id,
    this.knownForDepartment,
    this.name,
    this.originalName,
    this.popularity,
    this.profilePath,
    this.castId,
    this.character,
    this.creditId,
    this.order,
    this.job,
  });
  Actor.fromJsonMap(Map<String, dynamic> json) {
    adult = json['adult'];
    gender = json['gender'];
    id = json['id'];
    knownForDepartment = json['known_for_department'];
    name = json['name'];
    originalName = json['original_name'];
    popularity = json['popularity'];
    profilePath = json['profile_path'];
    castId = json['cast_id'];
    character = json['character'];
    creditId = json['credit_id'];
    order = json['order'];
  }
  String getfoto() => (profilePath != null)
      ? 'https://image.tmdb.org/t/p/w500/$profilePath'
      : 'https://image.flaticon.com/icons/png/512/16/16480.png';
}
